# Generated by Django 5.2.4 on 2025-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_article_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='publisher',
        ),
        migrations.AddField(
            model_name='customuser',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='news.publisher'),
        ),
    ]
