# Generated by Django 5.2.4 on 2025-07-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_customuser_publisher_customuser_publishers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='journalist',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
